### ISSUE TITLE
After upgrade it is not working

### ISSUE THREAD

**Issue by wacher74** [pinkywafer/Anniversaries#10]
Hello,

I used this cool stuff until today. I upgraded it to latest version and I'm sad now :(

```
Log Details (ERROR)
Thu Nov 28 2019 08:50:11 GMT+0100 (Central European Standard Time)
Error while setting up platform anniversaries
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/anniversaries/sensor.py", line 33, in async_setup_platform
    async_add_entities([anniversaries(hass, discovery_info)], True)
  File "/config/custom_components/anniversaries/sensor.py", line 44, in __init__
    self._name = config.get(CONF_NAME)
AttributeError: 'NoneType' object has no attribute 'get'
```

I have 3 sensor, each of them throw this message.

**Comment by wacher74** [comment]
Sorry, I didn't read the upgrade readme.
