### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by sonybansi** [pinkywafer/Anniversaries#125]
`Logger: homeassistant.components.sensor
Source: custom_components/anniversaries/sensor.py:64
Integration: Sensor (documentation, issues)
First occurred: 11:05:12 PM (1 occurrences)
Last logged: 11:05:12 PM

Error while setting up anniversaries platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/anniversaries/sensor.py", line 44, in async_setup_entry
    async_add_devices([anniversaries(hass, config_entry.data)], True)
  File "/config/custom_components/anniversaries/sensor.py", line 64, in __init__
    self.entity_id = generate_entity_id(ENTITY_ID_FORMAT, self._id_prefix + self._name, [])
TypeError: can only concatenate str (not "NoneType") to str
`

**Comment by pinkywafer** [comment]
closing as unable to replicate and no further information given.  If you still have this issue, please reopen the issue and give details of your configuration.
