### ISSUE TITLE
2024.11.0 HA update

### ISSUE THREAD

**Issue by VagnPetersen** [pinkywafer/Anniversaries#174]
After updating to HA 2024.11.0 Anniversaries does not work.

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 19:52:44 (1 occurrences)
Last logged: 19:52:44

Setup failed for custom integration 'anniversaries': Unable to import component: No module named 'integrationhelper'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/anniversaries/__init__.py", line 6, in <module>
    from integrationhelper.const import CC_STARTUP_VERSION
ModuleNotFoundError: No module named 'integrationhelper'

**Comment by BebeMischa** [comment]
Type of HA install?
Version of HA?
Version of Anniversaries?

**Comment by VagnPetersen** [comment]
HA:
Core 2024.11.1
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.2

Anniversaries 6.0.0

**Comment by k8ieone** [comment]
Same issue - HA 2024.11.3, FE 20241106.2

**Comment by k8ieone** [comment]
Installing `integrationhelper` using pip fixed the issue and the integration works.
