### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by bt-beardedtechie** [pinkywafer/Anniversaries#180]
Error setting up Anniversaries:

I'm getting the following error message since this morning when I updated to version 6.0.1:

Error

> Config flow could not be loaded: {"message":"Handler OptionsFlowManager doesn't support step init"}

Log file entry:

> Logger: homeassistant.config_entries
> Source: config_entries.py:640
> First occurred: 11:53:11 AM (3 occurrences)
> Last logged: 12:46:19 PM

```
Error setting up entry configuration.yaml for anniversaries
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/anniversaries/__init__.py", line 56, in async_setup_entry
    await hass.config_entries.async_remove(config_entry.entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1921, in async_remove
    unload_success, entry = await self._async_remove(entry_id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1937, in _async_remove
    async with entry.setup_lock:
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.13/asyncio/locks.py", line 110, in acquire
    await fut
asyncio.exceptions.CancelledError: Global task timeout
```

Additionally, this Warning shows up even with version 6.0.1:

> Logger: homeassistant.helpers.frame
> Source: helpers/frame.py:324
> First occurred: 12:35:19 PM (1 occurrences)
> Last logged: 12:35:19 PM

`Detected that custom integration 'anniversaries' sets option flow config_entry explicitly, which is deprecated at custom_components/anniversaries/config_flow.py, line 209: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please report it to the author of the 'anniversaries' custom integration`

**Comment by fft1010** [comment]
Same here.
Symptom… HA takes ages to start, and it complains somehow about anniversaries stopping it from working. I needed to make a full new install of HA, and than installed with the last backup. 6.0.0 worked just fine.

thank you
Juergen

**Comment by BertrumUK** [comment]
Same for me. Stops HA from starting. Going to rollback. 

Rolled back to 6.0.0 and HA starts as normal now. This release needs pulling.

**Comment by BebeMischa** [comment]
My Home assistant instance restarted after the the 6.0.1 update with the almost magical message in the core log: There are no issues.

Core 2024.12.2
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.7


Nice!

**Comment by j-inc** [comment]
Can confirm I'm experiencing the same behavior with 6.0.1. Rolling back to 6.0.0 solved the issue.

**Comment by I-G-1-1** [comment]
Same issue here, reverted to 6.0.0 for now.

**Comment by leonwebcreators** [comment]
Ditto here, rolled back to 6.0.0

**Comment by RedNo7** [comment]
Same issue here - 6.0.1 fails to setup.  Rolled back to 6.0.0 which is fine.

**Comment by cweakland** [comment]
As a workaround, you can remove your old yaml config and set it up using the GUI, everything seems to work fine.

**Comment by DrSpaldo** [comment]
As others, I am getting the same error with 6.0.1. @pinkywafer  are you able to have a look? I will roll back today

**Comment by SavageAUS** [comment]
> As a workaround, you can remove your old yaml config and set it up using the GUI, everything seems to work fine.

It has a GUI?

Anyway, same issue here, rolling back to 6.0.0 resolves the issue.

**Comment by mpepping** [comment]
> As a workaround, you can remove your old yaml config and set it up using the GUI, everything seems to work fine.

Removing anniversaries from yaml and setting it up in the UI fixed it for me as well.

**Comment by Shaun-Harrison** [comment]
Is UI rather than yaml going to be the way going forward? Not wanting to remove yaml unless its unsupported

**Comment by mn-box** [comment]
I have many entities, which would all need to be entered manually in the UI?

**Comment by I-G-1-1** [comment]
I also have many anniversaries and I really hope I don't have to manually enter all my anniversaries by hand in the UI. 
Using the .yaml was really faster than have to make infinite click on menù and sub-menù in the UI.
While using .yaml copy, paste and some changes was enought to add an anniversary.

**Comment by perlchamp** [comment]
My system is up-to-date, and i have no problems to install it via GUI. I installed it today via HACS and then add the integration in HA (via devices & services).
There you can create new entries. The configuration is simple, but ...
I'm a beginner, and now i'm trying to display all entries, that match the current month, with date of birth in the right order.
Any tips for that ?

Many thanks in advance !

**Comment by I-G-1-1** [comment]
> I'm a beginner, and now i'm trying to display all entries, that match the current month, with date of birth in the right order.
> Any tips for that 

Please don't hijack off-topic this thread. Open another issue asking for help. Thanks

**Comment by ekkesa** [comment]
Seems 6.0.1 is still causing timeouts when upgrading.

**Comment by DrSpaldo** [comment]
> Seems 6.0.1 is still causing timeouts when upgrading.

Been no updates since 6.0.1 and the issue isn’t fixed, hopefully the project isn’t dead but doesn’t look good

**Comment by RedNo7** [comment]
wow - just installed and assumed I was doing something wrong.

Also working perfectly after rolling back to 6.0.0
