### ISSUE TITLE
'datetime.date' object has no attribute 'date'

### ISSUE THREAD

**Issue by JonGilmore** [pinkywafer/Anniversaries#28]
Getting the following exception in my logs for a person who just had a birthday yesterday.

```
2020-02-17 08:55:31 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.redacteds_birthday fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/config/custom_components/anniversaries/sensor.py", line 104, in async_update
    if today < self._date.date():
AttributeError: 'datetime.date' object has no attribute 'date'
```

The person's bday is listed in my yaml file as follows: 
```
    - name: redacteds Birthday
      date: "02-16"
```
Thoughts?

**Comment by pinkywafer** [comment]
I'll look into it when I get chance

**Comment by pinkywafer** [comment]
Ok. Thanks. I've spotted the issue... will fix and release update later
